In [12]:
import os
os.chdir("training data csv file")

In [13]:
os.getcwd()

'f:\\PythonProject\\sklearn\\training data csv file'

In [21]:
import pandas as pd
import numpy as np

In [22]:
dataset = pd.read_csv('iris.csv')

In [187]:
dataset

sepal.length  sepal.width  petal.length  petal.width     variety
0             5.1          3.5           1.4          0.2      Setosa
1             4.9          3.0           1.4          0.2      Setosa
2             4.7          3.2           1.3          0.2      Setosa
3             4.6          3.1           1.5          0.2      Setosa
4             5.0          3.6           1.4          0.2      Setosa
5             5.4          3.9           1.7          0.4      Setosa
6             4.6          3.4           1.4          0.3      Setosa
7             5.0          3.4           1.5          0.2      Setosa
8             4.4          2.9           1.4          0.2      Setosa
9             4.9          3.1           1.5          0.1      Setosa
10            5.4          3.7           1.5          0.2      Setosa
11            4.8          3.4           1.6          0.2      Setosa
12            4.8          3.0           1.4          0.1      Setosa
13            4.3          3.0           1.1          0.1      Setosa
14            5.8          4.0           1.2          0.2      Setosa
15            5.7          4.4           1.5          0.4      Setosa
16            5.4          3.9           1.3          0.4      Setosa
17            5.1          3.5           1.4          0.3      Setosa
18            5.7          3.8           1.7          0.3      Setosa
19            5.1          3.8           1.5          0.3      Setosa
20            5.4          3.4           1.7          0.2      Setosa
21            5.1          3.7           1.5          0.4      Setosa
22            4.6          3.6           1.0          0.2      Setosa
23            5.1          3.3           1.7          0.5      Setosa
24            4.8          3.4           1.9          0.2      Setosa
25            5.0          3.0           1.6          0.2      Setosa
26            5.0          3.4           1.6          0.4      Setosa
27            5.2          3.5           1.5          0.2      Setosa
28            5.2          3.4           1.4          0.2      Setosa
29            4.7          3.2           1.6          0.2      Setosa
30            4.8          3.1           1.6          0.2      Setosa
31            5.4          3.4           1.5          0.4      Setosa
32            5.2          4.1           1.5          0.1      Setosa
33            5.5          4.2           1.4          0.2      Setosa
34            4.9          3.1           1.5          0.2      Setosa
35            5.0          3.2           1.2          0.2      Setosa
36            5.5          3.5           1.3          0.2      Setosa
37            4.9          3.6           1.4          0.1      Setosa
38            4.4          3.0           1.3          0.2      Setosa
39            5.1          3.4           1.5          0.2      Setosa
40            5.0          3.5           1.3          0.3      Setosa
41            4.5          2.3           1.3          0.3      Setosa
42            4.4          3.2           1.3          0.2      Setosa
43            5.0          3.5           1.6          0.6      Setosa
44            5.1          3.8           1.9          0.4      Setosa
45            4.8          3.0           1.4          0.3      Setosa
46            5.1          3.8           1.6          0.2      Setosa
47            4.6          3.2           1.4          0.2      Setosa
48            5.3          3.7           1.5          0.2      Setosa
49            5.0          3.3           1.4          0.2      Setosa
50            7.0          3.2           4.7          1.4  Versicolor
51            6.4          3.2           4.5          1.5  Versicolor
52            6.9          3.1           4.9          1.5  Versicolor
53            5.5          2.3           4.0          1.3  Versicolor
54            6.5          2.8           4.6          1.5  Versicolor
55            5.7          2.8           4.5          1.3  Versicolor
56            6

In [81]:
x = dataset.iloc[:,:4].values

In [188]:
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [82]:
from sklearn.preprocessing import LabelEncoder
lableencode_y = LabelEncoder()

y = lableencode_y.fit_transform(dataset.iloc[:,4].values)

In [83]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [84]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2)

In [85]:
from sklearn.linear_model import LogisticRegression
logmodel = LogisticRegression()
logmodel.fit(x_train, y_train)

C:\Users\PARAS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [87]:
y_pred = logmodel.predict(x_test)

In [88]:
y_pred

array([2, 1, 2, 0, 2, 2, 2, 0, 2, 2, 1, 1, 0, 0, 2, 2, 2, 1, 0, 0, 1, 2,
       2, 0, 0, 1, 0, 0, 0, 0])

In [89]:
y_test

array([2, 1, 2, 0, 2, 2, 2, 0, 2, 2, 1, 1, 0, 0, 2, 2, 2, 1, 0, 0, 2, 2,
       2, 0, 0, 1, 0, 0, 0, 0])

In [92]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[12,  0,  0],
       [ 0,  5,  0],
       [ 0,  1, 12]], dtype=int64)

In [150]:
f"Accuracy of the Model :- {round((12 + 5 + 12) / (12 + 5 + 12 + 1) * 100, 3)}%"

'Accuracy of the Model :- 96.667%'

In [116]:
from sklearn.neighbors import KNeighborsClassifier
classifier_knn = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier_knn.fit(x_train, y_train)

KNeighborsClassifier()

In [117]:
y_pred = classifier_knn.predict(x_test)

In [118]:
confusion_matrix(y_test, y_pred)

array([[12,  0,  0],
       [ 0,  5,  0],
       [ 0,  0, 13]], dtype=int64)

In [149]:
f"Accuracy of the Model :- {round((12 + 5 + 13) / (12 + 5 + 13 + 1) * 100, 3)}%"

'Accuracy of the Model :- 96.774%'

In [122]:
from sklearn.naive_bayes import GaussianNB
classifier_nb = GaussianNB()
classifier_nb.fit(x_train, y_train)

GaussianNB()

In [123]:
y_pred = classifier_nb.predict(x_test)

In [125]:
confusion_matrix(y_test, y_pred)

array([[12,  0,  0],
       [ 0,  5,  0],
       [ 0,  1, 12]], dtype=int64)

In [151]:
f"Accuracy of the Model :- {round((12 + 5 + 12) / (12 + 5 + 12 + 1) * 100, 3)}%"

'Accuracy of the Model :- 96.667%'

In [162]:
from sklearn.svm import SVC
classifier_svm_sigmoid = SVC(kernel = 'sigmoid')
classifier_svm_sigmoid.fit(x_train, y_train)

SVC(kernel='sigmoid')

In [163]:
y_pred = classifier_svm_sigmoid.predict(x_test)

In [164]:
confusion_matrix(y_test, y_pred)

array([[ 0, 12,  0],
       [ 0,  5,  0],
       [ 0, 13,  0]], dtype=int64)

In [165]:
f"Accuracy of the Model :- {round((5) / (12+5+13) * 100, 3)}%"

'Accuracy of the Model :- 16.667%'

In [166]:
from sklearn.svm import SVC
classifier_svm_linear = SVC(kernel = 'linear')
classifier_svm_linear.fit(x_train, y_train)

SVC(kernel='linear')

In [167]:
y_pred = classifier_svm_linear.predict(x_test)

In [168]:
confusion_matrix(y_test, y_pred)

array([[12,  0,  0],
       [ 0,  5,  0],
       [ 0,  0, 13]], dtype=int64)

In [169]:
f"Accuracy of the Model :- {round((12 + 5 + 13) / (12 + 5 + 13) * 100, 3)}%"

'Accuracy of the Model :- 100.0%'

In [170]:
from sklearn.svm import SVC
classifier_svm_rbf = SVC(kernel = 'rbf')
classifier_svm_rbf.fit(x_train, y_train)

SVC()

In [171]:
y_pred = classifier_svm_rbf.predict(x_test)

In [172]:
confusion_matrix(y_test, y_pred)

array([[12,  0,  0],
       [ 0,  5,  0],
       [ 0,  1, 12]], dtype=int64)

In [173]:
f"Accuracy of the Model :- {round((12 + 5 + 12) / (12 + 5 + 12 + 1) * 100, 3)}%"

'Accuracy of the Model :- 96.667%'

In [174]:
from sklearn.svm import SVC
classifier_svm_poly = SVC(kernel = 'poly')
classifier_svm_poly.fit(x_train, y_train)

SVC(kernel='poly')

In [175]:
y_pred = classifier_svm_poly.predict(x_test)

In [176]:
confusion_matrix(y_test, y_pred)

array([[12,  0,  0],
       [ 0,  5,  0],
       [ 0,  1, 12]], dtype=int64)

In [177]:
f"Accuracy of the Model :- {round((12 + 5 + 12) / (12 + 5 + 12 + 1) * 100, 3)}%"

'Accuracy of the Model :- 96.667%'

In [178]:
from sklearn.tree import DecisionTreeClassifier
classifier_dt = DecisionTreeClassifier(criterion='entropy')
classifier_dt.fit(x_train, y_train)

DecisionTreeClassifier(criterion='entropy')

In [179]:
y_pred = classifier_dt.predict(x_test)

In [180]:
confusion_matrix(y_test, y_pred)

array([[12,  0,  0],
       [ 0,  5,  0],
       [ 0,  1, 12]], dtype=int64)

In [181]:
f"Accuracy of the Model :- {round((12 + 5 + 12) / (12 + 5 + 12 + 1) * 100, 3)}%"

'Accuracy of the Model :- 96.667%'

In [183]:
from sklearn.ensemble import RandomForestClassifier
classifier_rf = RandomForestClassifier(n_estimators=3, criterion='entropy')
classifier_rf.fit(x_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=3)

In [184]:
y_pred = classifier_rf.predict(x_test)

In [185]:
confusion_matrix(y_test, y_pred)

array([[12,  0,  0],
       [ 0,  5,  0],
       [ 0,  1, 12]], dtype=int64)

In [186]:
f"Accuracy of the Model :- {round((12 + 5 + 12) / (12 + 5 + 12 + 1) * 100, 3)}%"

'Accuracy of the Model :- 96.667%'